title: "[Idea]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an idea! Please explain your idea clearly so we can understand the value it brings.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your idea related to a problem? Please describe.
      placeholder: I am frustrated when...
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: I would like to be able to...
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: "Have you considered any alternatives? Why didn't they work?"
